# Project information
site_name: OSharp 文档中心
site_description: osharp framework documents with markdown
site_author: osharp.org
site_url: https://docs.osharp.org/

repo_name: i66soft/osharp
repo_url: https://github.com/i66soft/osharp
edit_uri: "https://github.com/i66soft/osharp-docs/edit/master/docs"

# Copyright
copyright: 'Copyright &copy; 2014 - 2019 OSHARP.ORG'

theme:
  name: 'material'
  language: zh
  feature:
    tabs: true
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "\uE80C"
    
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 快速上手:
    - OSharp简介: quick/intro.md
    - 快速开始: quick/start.md
    - 步步为营:
      - 添加业务模块: quick/steps/pack.md
      - 添加业务模块实体/DTO: quick/steps/entity-dto.md
      - 添加业务模块服务: quick/steps/service.md
      - 添加业务模块对外API: quick/steps/controller.md
      - 添加前端Angular模块: quick/steps/ng-module.md
    - 权限系统:
      - 权限系统概述: quick/permiss/index.md
      - 功能，实体，模块管理: quick/permiss/function-entityinfo-module.md
      - 角色管理: quick/permiss/role.md
      - 用户管理: quick/permiss/user.md
      - 给角色分配数据权限: quick/permiss/role-entityinfo.md
  - 设计详解:
    - 概述: explain/index.md
    - OSharp总体设计: explain/overall-design.md
    - OSharp启动流程: explain/startup.md
    - 功能模块剖析:
      - 功能模块概述: explain/packs/index.md
      - 核心模块: explain/packs/core.md
      - 依赖注入模块: explain/packs/dependency.md
      - 事件总线模块: explain/packs/eventbus.md
      - AspNetCore模块: explain/packs/aspnetcore.md
      - AutoMapper模块: explain/packs/automapper.md
      - EFCore模块: 
        - EFCore模块概述: explain/packs/efcore/index.md
        - 实体/仓储设计: explain/packs/efcore/entity-repository.md
        - 数据上下文设计: explain/packs/efcore/dbcontext.md
        - 工作单元/事务设计: explain/packs/efcore/unitofwork-transaction.md
        - 数据迁移: explain/packs/efcore/migration.md
        - 各数据驱动应用: explain/packs/efcore/database-provider.md
      - Redis模块: explain/packs/redis.md
      - 数据实体模块: explain/packs/entityinfo.md
      - 身份认证模块: explain/packs/identity.md
      - Mvc模块: explain/packs/aspnetcore-mvc.md
      - SignalR模块: explain/packs/signalr.md
      - Hangfire模块: explain/packs/hangfire.md
      - 权限安全模块: explain/packs/security.md
      - 缓存服务: explain/services/caching.md
      - 查询服务: explain/services/filter.md
  - 视频教程: 
    - 概述: videos/index.md
  - API文档:
    - 概述: api/index.md
  - 常见问题: 
    - 概述: faq/index.md
  - 关于:
    - 关于OSharp: about/index.md
    - 更新日志: about/update-logs.md
    - 许可证: about/licence.md
